package auth_test

import (
	"net/http"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/widroach/chirpy/internal/auth"
)

func TestMakeJWT(t *testing.T) {
	tests := []struct {
		name        string
		userID      uuid.UUID
		tokenSecret string
		expiresIn   time.Duration
		wantErr     bool
	}{
		{
			name:        "valid token",
			userID:      uuid.New(),
			tokenSecret: "test-secret",
			expiresIn:   time.Hour,
			wantErr:     false,
		},
		{
			name:        "already expired token",
			userID:      uuid.New(),
			tokenSecret: "test-secret",
			expiresIn:   -time.Minute,
			wantErr:     false, // MakeJWT itself should succeed even if expiry is in the past
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, gotErr := auth.MakeJWT(tt.userID, tt.tokenSecret, tt.expiresIn)
			if gotErr != nil {
				if !tt.wantErr {
					t.Fatalf("MakeJWT() unexpected error: %v", gotErr)
				}
				return
			}
			if tt.wantErr {
				t.Fatal("MakeJWT() succeeded unexpectedly")
			}
			if got == "" {
				t.Fatalf("MakeJWT() returned empty token")
			}

			// Verify token can be validated with the same secret (expired case may still produce a token,
			// validation of expiry is covered in ValidateJWT tests).
			uid, err := auth.ValidateJWT(got, tt.tokenSecret)
			if err != nil && tt.expiresIn > 0 {
				t.Fatalf("ValidateJWT() failed for token generated by MakeJWT: %v", err)
			}
			if tt.expiresIn > 0 && uid != tt.userID {
				t.Fatalf("ValidateJWT() = %v, want %v", uid, tt.userID)
			}
		})
	}
}

func TestValidateJWT(t *testing.T) {
	secret := "validate-secret"
	userID := uuid.New()

	validToken, err := auth.MakeJWT(userID, secret, time.Hour)
	if err != nil {
		t.Fatalf("setup MakeJWT failed: %v", err)
	}

	expiredToken, err := auth.MakeJWT(userID, secret, -time.Minute)
	if err != nil {
		t.Fatalf("setup expired MakeJWT failed: %v", err)
	}

	tests := []struct {
		name        string
		tokenString string
		tokenSecret string
		want        uuid.UUID
		wantErr     bool
	}{
		{
			name:        "valid token and secret",
			tokenString: validToken,
			tokenSecret: secret,
			want:        userID,
			wantErr:     false,
		},
		{
			name:        "wrong secret",
			tokenString: validToken,
			tokenSecret: "wrong-secret",
			want:        uuid.UUID{},
			wantErr:     true,
		},
		{
			name:        "expired token",
			tokenString: expiredToken,
			tokenSecret: secret,
			want:        uuid.UUID{},
			wantErr:     true,
		},
		{
			name:        "malformed token",
			tokenString: "not-a-token",
			tokenSecret: secret,
			want:        uuid.UUID{},
			wantErr:     true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, gotErr := auth.ValidateJWT(tt.tokenString, tt.tokenSecret)
			if gotErr != nil {
				if !tt.wantErr {
					t.Fatalf("ValidateJWT() unexpected error: %v", gotErr)
				}
				return
			}
			if tt.wantErr {
				t.Fatal("ValidateJWT() succeeded unexpectedly")
			}
			if got != tt.want {
				t.Fatalf("ValidateJWT() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestGetBearerToken(t *testing.T) {
	tests := []struct {
		name    string
		headers http.Header
		want    string
		wantErr bool
	}{
		{
			name:    "valid token",
			headers: http.Header{"Authorization": []string{"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiYjk1NzNmNjktYTA0ZS00MTkyLTk2YmQtMDQwNjgxMWFkYjBiIiwiZXhwIjoxNzg1MjgxNDkwLCJpYXQiOjE3ODUyODE0OTB9.h-8FkjDaWmJXdhsSW1zJswnT8fSAyMAU_5OhsQjlMVY"}},
			want:    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiYjk1NzNmNjktYTA0ZS00MTkyLTk2YmQtMDQwNjgxMWFkYjBiIiwiZXhwIjoxNzg1MjgxNDkwLCJpYXQiOjE3ODUyODE0OTB9.h-8FkjDaWmJXdhsSW1zJswnT8fSAyMAU_5OhsQjlMVY",
			wantErr: false,
		},
		{
			name:    "includes spaces",
			headers: http.Header{"Authorization": []string{"Bearer                   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiYjk1NzNmNjktYTA0ZS00MTkyLTk2YmQtMDQwNjgxMWFkYjBiIiwiZXhwIjoxNzg1MjgxNDkwLCJpYXQiOjE3ODUyODE0OTB9.h-8FkjDaWmJXdhsSW1zJswnT8fSAyMAU_5OhsQjlMVY"}},
			want:    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiYjk1NzNmNjktYTA0ZS00MTkyLTk2YmQtMDQwNjgxMWFkYjBiIiwiZXhwIjoxNzg1MjgxNDkwLCJpYXQiOjE3ODUyODE0OTB9.h-8FkjDaWmJXdhsSW1zJswnT8fSAyMAU_5OhsQjlMVY",
			wantErr: false,
		},
		{
			name:    "missing token",
			headers: http.Header{"Authorization": []string{"Bearer"}},
			want:    "",
			wantErr: true,
		},
		{
			name:    "missing header",
			headers: http.Header{},
			want:    "",
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, gotErr := auth.GetBearerToken(tt.headers)
			if gotErr != nil {
				if !tt.wantErr {
					t.Errorf("GetBearerToken() failed: %v", gotErr)
				}
				return
			}
			if tt.wantErr {
				t.Fatal("GetBearerToken() succeeded unexpectedly")
			}
			if got != tt.want {
				t.Errorf("GetBearerToken() = %v, want %v", got, tt.want)
			}
		})
	}
}
