### GET /api/healthz
GET {{baseUrl}}/api/healthz

### GET /admin/metrics
GET {{baseUrl}}/admin/metrics

### POST /admin/reset
POST {{baseUrl}}/admin/reset

{

}

### Create a new user
POST {{baseUrl}}/api/users

{
    "email": "user@example.com"
}

### Get a single chirp
GET {{baseUrl}}/api/chirps/6cbe6e39-d1fc-457d-9e95-99b2ec106735

### Get all chirps
GET {{baseUrl}}/api/chirps

### Create new chirp
POST {{baseUrl}}/api/chirps

{
    "body": "Hi, I am new here!",
    "user_id": "26f1c59d-71ed-4b64-91ea-4ac83a7b5ebf"
}
