### GET /api/healthz
GET {{baseUrl}}/api/healthz

### GET /admin/metrics
GET {{baseUrl}}/admin/metrics

### POST /admin/reset
POST {{baseUrl}}/admin/reset

{

}

### Create a new user
POST {{baseUrl}}/api/users

{
    "email": "user@example.com"
}

### Create new chirp
POST {{baseUrl}}/api/chirps

{
    "body": "Hi, I am new here!",
    "user_id": "ba3f1aa1-b5fc-4cf5-85a6-002cd57878cd"
}
